version: '3.4'

volumes:
  sugoi_socket:
      

services:
  nginx:
    image: nginx:1.13
    container_name: django.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
      - ./nginx/log:/var/log/nginx
      - sugoi_socket:/var/run
    depends_on:
      - web

  mysql:
    build: ./sql
    container_name: django.mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  web:
    build: ./web
    container_name: django.web
    command: uwsgi --ini /code/sugoi_site/django.ini
    volumes:
      - ./src:/code
      - ./static:/static
      - sugoi_socket:/var/run
    expose:
      - "8001"
    depends_on:
      - mysql

    