# Generated by Django 3.0.2 on 2020-03-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('thumnail_url', models.TextField(blank=True, null=True)),
                ('published_at', models.CharField(blank=True, max_length=30, null=True)),
                ('subscriber_num', models.IntegerField(blank=True, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('total_view', models.BigIntegerField(blank=True, null=True)),
                ('total_video', models.IntegerField(blank=True, null=True)),
                ('last_up', models.DateTimeField()),
                ('category_game', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
    ]
