# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with: # shimataro/ssh-key-actionに渡すパラメーター
        key: ${{ secrets.SSH_KEY }} # 必須
        known_hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
        name: streambox-instance1-ssh
    - name: ssh key generate
      run: echo ”$SSH_PRIVATE_KEY” ＞ key ＆＆ chmod 600 key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
    - name: migrate database
      run: ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ka1ryu@34.83.27.41 ’touch hoge.py’
