on:
    pull_request:
        types: closed
        branches:
            - 'master'
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY }} # 必須
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
        name: testpem
    - name: ssh keygen
      run: ssh-keygen -R 34.83.27.41
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
    - uses: actions/checkout@master
    - name: auto-deploy
      if: github.event.pull_request.merged == true
      run: ssh ka1ryu@34.83.27.41 -o 'StrictHostKeyChecking=no' -i ~/.ssh/testpem "cd /home/streambox_devlop/stream-box/ && git pull origin master"
